



server:
  port: 80


spring:
  datasource:
    url: jdbc:mysql://192.168.35.3:3306/ck_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: 'yyyy-MM-dd HH:mm:ss'
  thymeleaf:
    cache: false


logging:
  level:
    org.ck.teach.teachplatform: debug

